### ISSUE TITLE
Any tool to Render vulkan shader fragments with version, 310es.

### ISSUE THREAD

**Issue by varnam379** [google/graphicsfuzz#1008]
Hi,

I am looking for any tool  which renders vulkan fragment shaders with version, 310es in order to reproduce the crashes observed after running shaders on vulkan worker applications.

I need to verify if the system or driver crashes after running the fragment shaders.

**Comment by paulthomson** [comment]
Hi. We use Amber for this purpose:

https://github.com/google/amber

By the way, if you are using GraphicsFuzz to test Vulkan, we recommend using [gfauto](https://github.com/google/graphicsfuzz/tree/master/gfauto#gfauto), which runs GraphicsFuzz to generate GLSL shaders, converts them to SPIR-V, then runs them using Amber on the current Vulkan device, or SwiftShader Vulkan, or on an Android device that supports Vulkan. Unfortunately, there is not much documentation, but we should fix that. Bugs are output in a `reports/` directory.

**Comment by varnam379** [comment]
Is there windows support for gfauto? They have mentioned saying it supports Linux & unlikely to work on Windows. We wanted to test it on Windows

**Comment by paulthomson** [comment]
I haven’t run it recently on Windows, but it should work to a certain extent. There are a few potential issues, although most of these issues apply even if you just use GraphicsFuzz with the Vulkan worker. 

GraphicsFuzz creates lots of subprocesses, and this is much slower on Windows. 

Many of the tools (like glslangValidator, spirv-opt) are compiled in the Debug configuration with asserts, and an assertion failure will cause a pop up dialogue on Windows.

On Linux, we use ‘catchsegv program ...’ to get a stack trace when ‘program’ crashes. We don’t have a similar tool for Windows. I tried to use ‘cdb’ instead, but this is extremely slow. I recommend running ‘gfauto_fuzz’ with the ‘--allow_no_stack_traces’ arg and don’t put ‘cdb’ on your PATH (it probably won’t be on your PATH anyway). You won’t get a stack trace if the graphics driver or a tool crashes, so when gfauto reduces (shrinks) a shader, the bug that is triggered may change. But you will still end up with a shader that causes a crash. And if the driver can be made to produce a stack trace on crashes, then that could work well.

**Comment by afd** [comment]
@varnam379 I'm going to close this, but do open a new issue if you have some follow-on questions.
