### ISSUE TITLE
Solution for frag2vert "discard" operation

### ISSUE THREAD

**Issue by jarisiru** [google/graphicsfuzz#1053]
Currently frag2vert conversion turns discard into a no-op, which results in the shader continuing execution and the results are rather undefined.

This could be solved by instead passing a boolean variable from the vertex shader to fragment which then would run the discard operation. While the rest of the vertex shader would still be executed (which doesn't happen with the actual discard op), the end result would be discarded, so the end result would be deterministic.

**Comment by afd** [comment]
@jarisiru I think this sounds like a good solution, so I suggest you work on it.

**Comment by jarisiru** [comment]
https://github.com/google/graphicsfuzz/pull/1080
