### ISSUE TITLE
Reducer: reduce double brackets (( )) to simple ones ( ) after final _GLF_ macro replacement

### ISSUE THREAD

**Issue by hevrard** [google/graphicsfuzz#110]
This:

`if ( _GLF_BLAH((X)) ) {}`

may lead to this at the very end of reduction, when _GLF_ macros are replaced by their expension:

`if ((X)) {}`

But this double brackets could be reduced to:

`if (X) {}`

**Comment by afd** [comment]
In #471 I have added a test to illustrate this problem.  When the issue is fixed, that test should pass.  (It would be worth adding a few others like it.)

**Comment by jiradeto** [comment]
Fixed by #489.
