### ISSUE TITLE
Unreleased Resource: Streams

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/graphicsfuzz#1101]
https://github.com/google/graphicsfuzz/blob/c775138567a57fd45a2ae6b6f9506af8ecb7fe29/server/src/main/java/com/graphicsfuzz/server/webui/WebUi.java#L316

The program can potentially fail to release a system resource.

**Comment by afd** [comment]
We should retire the WebUI in favour of gfauto, especially once we have ShaderTrap integration, thus closing WebUI-related issues.
