### ISSUE TITLE
CI should build and run some tests that exercise the binaries on several platforms

### ISSUE THREAD

**Issue by paulthomson** [google/graphicsfuzz#115]
And try different versions of JDK

**Comment by afd** [comment]
Removing this from the milestone.  We definitely want it, but are not going to have it before the coming release so will have to do this manually for the release.

**Comment by paulthomson** [comment]
Command line tests were added in #199 

GitHub Actions CI was added in #826 and this supports multiple JDK versions (although we don't run them yet)
