### ISSUE TITLE
Use image comparison metric that considers alpha channel

### ISSUE THREAD

**Issue by afd** [google/graphicsfuzz#164]
The image histogram and PSNR metrics that GraphicsFuzz uses do not consider the alpha channel.  They thus miss shader compiler bugs that lead to incorrect alpha computation.

We should consider ways to adjust these metrics so that they do consider alpha (or look at different metrics).

**Comment by hevrard** [comment]
Here is an implementation of SSIM metric, with alpha channel support:
https://pngquant.org/dssim.html

**Comment by afd** [comment]
In general the image histogram metric that we are using is pretty limited even despite lack of alpha channel support.  For example, I have found that it gives a distance of 0 between an image filled with vec4(0.0, 0.0, 0.0, 1.0) pixels and an image filled with vec4(1.0, 1.0, 1.0, 1.0) pixels.

**Comment by hevrard** [comment]
An idea is to switch from OpenCV to ImageMagick, which offers the following comparison metrics:
https://imagemagick.org/script/command-line-options.php#metric

Imagemagick has Java wrappers and is available via Maven:
http://www.jmagick.org/jmagick-doc/
https://mvnrepository.com/artifact/org.imagemagick

As I think OpenCV is used only for image comparison, we could then drop the OpenCV dependency.

**Comment by paulthomson** [comment]
Added histogram alpha support in #262

Added fuzzy difference algorithm in #271 Still need to integrate this algorithm but this issue is technically fixed.
