### ISSUE TITLE
shader_translator gives a "memory exhausted" error fairly easily, necessitating a workaround

### ISSUE THREAD

**Issue by afd** [google/graphicsfuzz#171]
Running:

shader_translator exhausts_shader_translator_memory.frag

on [this file, which must be renamed from .txt to .frag](https://github.com/google/graphicsfuzz/files/2677040/exhausts_shader_translator_memory.frag.txt)

leads to:

ERROR: 0:2823: '+' : memory exhausted

I have added a workaround to say that a shader is valid (according to shader_translator) when we get this error, otherwise we chuck away a lot of shaders and cannot reliably test whether we are generating valid shaders.

Let's check whether this reproduces on recent builds of shader_translator, and if so see whether it is intended behaviour.

**Comment by paulthomson** [comment]
Reported: https://bugs.chromium.org/p/angleproject/issues/detail?id=3028

**Comment by afd** [comment]
Perhaps we should look into fixing this one directly in shader_translator.

**Comment by afd** [comment]
The problem has apparently been fixed in shader_translator:

https://bugs.chromium.org/p/angleproject/issues/detail?id=3028#c6

We need to update the ANGLE build that we use and verify the fix, then can close this.

**Comment by paulthomson** [comment]
Updated ANGLE in #476
