### ISSUE TITLE
Consider bundling Amber

### ISSUE THREAD

**Issue by paulthomson** [google/graphicsfuzz#175]
This is probably best for usability.

**Comment by afd** [comment]
@paulthomson Please update your thoughts on this now that we use Amber.  Should we instead have an issue for bundling Amber automatically?

**Comment by paulthomson** [comment]
Yes

**Comment by paulthomson** [comment]
We now build Amber here: https://github.com/google/gfbuild-amber

We download it automatically in gfauto: https://github.com/google/graphicsfuzz/tree/master/gfauto
