### ISSUE TITLE
Provide an option to re-register a worker with the server

### ISSUE THREAD

**Issue by afd** [google/graphicsfuzz#180]
At present if a worker with name foo has previously connected to the server, if foo connects again with different platform info, it is rejected.  That's good as we want to avoid confusion.

But there are cases where someone might want to use a changed worker with the same name, reusing old test results, if they know what they're doing.

For this, we could provide a mechanism for the check to be over-ridden and the worker's new info to override the old info.  I guess having an extra field in the thrift message a worker sends to present itself to the server would do the trick.

**Comment by paulthomson** [comment]
By the way, I feel like one of the use cases was re-run an individual shader on the newer driver. We should provide the ability to do this, even if a shader family has no results on the device of interest.

**Comment by afd** [comment]
Obsolete due to gfauto being the preferred way to run graphicsfuzz.
