### ISSUE TITLE
Error in condition on detecting compute / image job clash?

### ISSUE THREAD

**Issue by hevrard** [google/graphicsfuzz#197]
https://github.com/google/graphicsfuzz/blob/f2d56185ac0205d1dcf41248db1cb724bcabea88/common/src/main/java/com/graphicsfuzz/common/util/ShaderJobFileOperations.java#L571

This test is valid if a ".comp" **or** a ".vert" file is present, shouldn't it be a **and** ?

Also, why not test the presence of a ".frag" file?

**Comment by paulthomson** [comment]
This is just for rendering using get image locally. Only .frag files are supported. If any other files are specified, then we fail.

We could indeed check that the .frag file is present.

**Comment by hevrard** [comment]
Oh ok, I though it was the check for clash of presence of both image and compute shaders.

Maybe the corresponding error message should be edited like:
Running vertex and compute shaders locally is not supported yet -> vertex **or** compute

**Comment by afd** [comment]
Closing as too low priority for fixing.
