### ISSUE TITLE
Irrelevant alpha channel in images from VkRunner

### ISSUE THREAD

**Issue by hevrard** [google/graphicsfuzz#202]
We rely on VkRunner image export which writes in PPM format, but PPM format does not support alpha channel. Hence VkRunner images all have alpha set to 1.0.

We should make sure to get alpha channel in images exported by Amber later on. As an alternative to PPM, another straighforward image format, with alpha support, is:
https://tools.suckless.org/farbfeld/

**Comment by paulthomson** [comment]
Closing this as we use amber now.
