### ISSUE TITLE
Remove version argument from generator and have the generator work out the version from the shader's version string.

### ISSUE THREAD

**Issue by afd** [google/graphicsfuzz#215]
Historically we didn't parse version info and instead had this passed in on the command line - convenient if one wanted to interpret the same shader code under various different GLSL versions.

However, in practice we don't rely on this, and it's getting increasingly painful to have a separation between the version string in a shader and a version string passed in on the command line, so we should only have the former.

**Comment by afd** [comment]
Fixed by #216

**Comment by paulthomson** [comment]
Minor issue: `Generate.java` still adds a positional argument `glsl-version`; I believe it is unused.

**Comment by paulthomson** [comment]
Fixed by #620
