### ISSUE TITLE
Build Vulkan worker for Linux as part of presubmit and in CI

### ISSUE THREAD

**Issue by afd** [google/graphicsfuzz#253]
I believe we don't build the Vulkan worker for Linux as part of our presubmit and CI processes.

It would be good if we could do this; seems like it should be easy given that we do it for Android.

**Comment by hevrard** [comment]
On branch add-vkworker-presubmit-ci (https://github.com/google/graphicsfuzz/tree/add-vkworker-presubmit-ci), the presubmit is done, the CI is in the works but is still failing.

Latest error report is here: https://travis-ci.org/google/graphicsfuzz/jobs/491901106
On line 829 you can see:
```
++export LD_LIBRARY_PATH=/home/travis/vulkan-sdk/1.1.97.0/x86_64/lib
++LD_LIBRARY_PATH=/home/travis/vulkan-sdk/1.1.97.0/x86_64/lib
```

Yet later the vulkan worker link stage fails:
`/usr/bin/ld: cannot find -lvulkan`

I'm a bit puzzled by this, @paulthomson can you have a look?

**Comment by afd** [comment]
It's not clear whether it's worth us doing this if we are moving towards Amber.

**Comment by afd** [comment]
@hevrard and @paulthomson do you agree that we should close this now since that worker is now classed as legacy?

**Comment by paulthomson** [comment]
Yes
