### ISSUE TITLE
Linux Vulkan worker fails due to VK_ERROR_LAYER_NOT_PRESENT

### ISSUE THREAD

**Issue by afd** [google/graphicsfuzz#270]
I find that the Linux Vulkan worker (original, not Amber) fails on a simple shader job with this error:

vulkan_worker.cc:126 CALL   vkEnumerateInstanceExtensionProperties(nullptr, &num_properties, nullptr)
vulkan_worker.cc:126 RETURN VK_SUCCESS
Num instance properties: 10
vulkan_worker.cc:130 CALL   vkEnumerateInstanceExtensionProperties(nullptr, &num_properties, properties)
vulkan_worker.cc:130 RETURN VK_SUCCESS
Extension #0: VK_KHR_external_fence_capabilities
Extension #1: VK_KHR_external_memory_capabilities
Extension #2: VK_KHR_external_semaphore_capabilities
Extension #3: VK_KHR_get_physical_device_properties2
Extension #4: VK_KHR_get_surface_capabilities2
Extension #5: VK_KHR_surface
Extension #6: VK_KHR_wayland_surface
Extension #7: VK_KHR_xcb_surface
Extension #8: VK_KHR_xlib_surface
Extension #9: VK_EXT_debug_report
Enable extension debug_report
vulkan_worker.cc:168 CALL   vkCreateInstance(&instance_create_info, nullptr, &instance_)
vulkan_worker.cc:168 RETURN VK_ERROR_LAYER_NOT_PRESENT

STATUS CRASH

**Comment by paulthomson** [comment]
This was because the Vulkan SDK was not installed properly. Closing this, as we favor amber now.
