### ISSUE TITLE
SwiftShader tests are slow

### ISSUE THREAD

**Issue by paulthomson** [google/graphicsfuzz#284]
This might be a performance regression in SwiftShader or it might be that more tests are able to run compared to before, so they seem slower. We should investigate.

Either way, we should revisit the size limit in `ReducerUnitTest.java`; we may be able to increase it once tests run faster.

Of course, also consider removing shaders from the blacklists in `ReducerUnitTest.java`.

**Comment by afd** [comment]
Closing as we want to improve gfauto CI instead.
