### ISSUE TITLE
runspv: no stack trace on Android

### ISSUE THREAD

**Issue by paulthomson** [google/graphicsfuzz#304]
Using the server to run some examples, I am seeing some logcat output but no stack trace. 

For amber.

**Comment by hevrard** [comment]
Have you tried to repro the crash and manually inspect the logcat to make sure that there is a stack trace for this crash?

**Comment by paulthomson** [comment]
Note: I think we will get a stack trace on Android, but I have not hit any driver crashes yet

**Comment by afd** [comment]
Confirmed that I hit a driver crash on Android and got a stack trace.  Success!
