### ISSUE TITLE
When viewing a result, information about the image metrics should be available

### ISSUE THREAD

**Issue by afd** [google/graphicsfuzz#321]
When you view an image result, you should be presented with info about the image metrics so that if the metrics disagree you can see which one thinks the images are different and decide to use that one for a reduction if appropriate.

Right now it's only possible to get this information via a back door.

I'm thinking something like this mock-up (though I am unsure whether we are currently looking at the results of PSNR):

![webui](https://user-images.githubusercontent.com/4739677/53562563-90d46200-3b49-11e9-95c4-f70d78935804.png)

**Comment by paulthomson** [comment]
Fixed in #328
