### ISSUE TITLE
Document how to use image diffs in webui

### ISSUE THREAD

**Issue by afd** [google/graphicsfuzz#339]
Make sure there are some tips on how to use the various image diffs in the documentation.

**Comment by hevrard** [comment]
Make a note about current limitations of the fuzzy diff to do with transparency and identical.

**Comment by afd** [comment]
We need to update the images in the Web UI under:

## Viewing shader family results

and

## Queuing a bad image reduction

as they have changed a bit due to the UI changes related to diffs.

**Comment by afd** [comment]
Fixed via #375
