### ISSUE TITLE
Remove compute shaders from results view in web UI

### ISSUE THREAD

**Issue by afd** [google/graphicsfuzz#347]
It is handy to be able to launch compute shader families using the web UI.  But currently their results are then available for viewing, but are not presented in a meaningful way.  Let's make it so that their results are not shown at all.  We can decide in future if we want them to be shown and implement proper support at that time.

**Comment by hevrard** [comment]
How can you reliably detect that a shader family is a compute shaders?

Is testing for the presence of `reference.comp` enough?

**Comment by paulthomson** [comment]
Fixed in #365
