### ISSUE TITLE
A tests to do with whether a script is executable fails under Windows

### ISSUE THREAD

**Issue by afd** [google/graphicsfuzz#370]
Under Windows, when I do mvn package I find that this test fails;

com.graphicsfuzz.reducer.tool.GlslReduceTest.checkCustomJudgeIsExecutable(GlslReduceTest.java:133)

The test tries to run a custom reduction with a non-executable interestingness script, and is intended to fail as the script should be detected as non-excetable, leading to an error.  (So its an "xfail" test.)  But under Windows trying to execute the script leads to a pop-up asking what program should be used to open the script, and the required exception is not raised.

@paulthomson would you be able to look at whether we can handle this under Windows?  If needed, it would be reasonable to skip that test under Windows.

**Comment by paulthomson** [comment]
Yes I think we should skip this test as I believe files are always considered executable under Windows.

**Comment by paulthomson** [comment]
Fixed in #371
