### ISSUE TITLE
Documentation unclear

### ISSUE THREAD

**Issue by afd** [google/graphicsfuzz#372]
There is a "must be" missing here.  I guess it is that in order to use the latest zip and applications, Java 8+, etc., must be on your path?

"
**Summary:** the latest release zip and worker applications, Java 8+, Python 3.5+, and (if you want to do Vulkan Android testing) `adb` on your path.
"

**Comment by paulthomson** [comment]
I think this is supposed to start with "you need" and then I think it makes sense?

**Comment by afd** [comment]
Fixed via #375
