### ISSUE TITLE
Linux: use SIGSEGV in case of timeout to get a stacktrace

### ISSUE THREAD

**Issue by hevrard** [google/graphicsfuzz#373]
We already wrap `catchsegv` calls by our own Popen() logic, and in case of timeout we send SIGKILL to the whole process group. It would be interesting to try to send SIGSEGV, as this may enable catchsegv to dump a stacktrace.

We could then see were wwas the process at the point of timeout.

This may not work as catchsegv itself will also receive the SIGSEGV.

**Comment by afd** [comment]
Obsolete.
