### ISSUE TITLE
Improve CustomMutatorServer

### ISSUE THREAD

**Issue by jonathanmetzman** [google/graphicsfuzz#381]
`CustomMutatorServer` needs some basic improvements such as:

* Allowing the port to be specified as an argument.
* Figuring out how to block until the full header is in.
* Allowing multiple libFuzzer processes to be used at once.
* Allowing multiple connections per server lifetime, so that the server doesn't need to be restarted if the first connection dies.

**Comment by jonathanmetzman** [comment]
I can't assign this issue to myself, though it should be that fixes it.

**Comment by jonathanmetzman** [comment]
As I mentioned though, I think it will be worth profiling before making these improvements, since the improvements will be a waste of time if we throw out the tcp server.

**Comment by afd** [comment]
Closing for now, let's reopen if we pick this up again.
