### ISSUE TITLE
runspv should convert shaders to hex, not spirv text (assembly)

### ISSUE THREAD

**Issue by paulthomson** [google/graphicsfuzz#388]

**Comment by afd** [comment]
I did consider that but opted for the text route as it is so much easier to read.  It's probably larger, but does that matter much?

**Comment by paulthomson** [comment]
I think there are some downsides to using text:

* We are relying on some version of spirv-as (internally used by Amber), which might be out of sync with the version of SPIRV-Tools we are using, and it might be annoying (and nontrivial) to have to update it and rebuild Amber etc.
* The spirv binary is not getting passed directly to the driver; it is first going through spirv-dis (on our side) and spirv-as (inside Amber). Not sure how much this matters though.
* Amber is essentially doing spirv-as *on the (Android) device*, which is potentially a bit inefficient, when we could just be doing it on the host.

But I agree text is much more convenient. If we do output hex, perhaps we should output a text version as well for convenience. We may even want to run spirv-dis and spirv-as on the host as a sanity check; I am guessing some of the "crashes" we have seen would then be in spirv-as (on the host) instead of amber (on the device), which is a bit easier to diagnose.

**Comment by paulthomson** [comment]
Hmm so the errors were not in spirv-as, which I suppose is not that surprising. I am undecided. Text might be fine really.
