### ISSUE TITLE
Reflective xss vulnerability

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/graphicsfuzz#392]
Hi!
We found multiple xss vulnerabilities in WebUi.java in the graphicsfuzz project. The details are as follows:
Taking the 1560 line as an example, the program receives the worker parameter and the queueType parameter in the request.When the queueType parameter is "worker", the program will string the worker parameters.
![图片](https://user-images.githubusercontent.com/39950310/54111293-83a75500-441e-11e9-8584-13282c355041.png)
Finally, the direct output on the 1582 line is on the page.
![图片](https://user-images.githubusercontent.com/39950310/54111390-b3565d00-441e-11e9-80de-bbff37d77181.png)

**Comment by afd** [comment]
We should retire the WebUI in favour of gfauto, especially once we have ShaderTrap integration, thus closing WebUI-related issues.
