### ISSUE TITLE
Enlarge test in OpaqueExpressionGeneratorTest so that it generates many expressions per shader, to get better coverage.

### ISSUE THREAD

**Issue by afd** [google/graphicsfuzz#411]
Right now, OpaqueExpressionGeneratorTest.testGeneratesValidExpressions generates, for each basic type, a little program that declares a variable of the given type and assigns it to an expression that has been mutated using an identity function.   For example:

void main() {
  float x0; x0 = _GLF_IDENTITY(1.0, max(1.0, _GLF_IDENTITY(1.0, clamp(1.0, 1.0, 1.0))));
}

or

void main() {
  vec3 x0; x0 = _GLF_IDENTITY(vec3(1.0), vec3(0.0, 0.0, 0.0) + (vec3(1.0)));
}

This doesn't achieve very high coverage of the identity function generation code.

We should make it so that instead each program has a large number of such variable-and-assignment pairs, e.g.:

void main() {
  vec3 x0; x0 = _GLF_IDENTITY(vec3(1.0), vec3(0.0, 0.0, 0.0) + (vec3(1.0)));
  vec3 x1; x1 = ...;
  vec3 x2; x2 = ...;
  vec3 x3; x3 = ...;
  ...
}

with e.g. 1000 variables being a good number per test.

**Comment by mmoanis** [comment]
Is there something still to be done here?

**Comment by afd** [comment]
Nothing more to be done for now: closed via #411.
