### ISSUE TITLE
Amber may require a specific version of the NDK to build

### ISSUE THREAD

**Issue by paulthomson** [google/graphicsfuzz#454]
We have received reports of this. We should fix this, even if we end up pre-building amber for Android.

**Comment by paulthomson** [comment]
Looks like the SDK and NDK version that we suggest using in the GraphicsFuzz instructions work fine on all platforms, but the Amber instructions suggest a different version. We should make sure we clarify this.

**Comment by afd** [comment]
We should revamp the docs so that they use a pure gfauto workflow, in which case this isn't relevant.
