### ISSUE TITLE
Complete built-in function support for GLSL ES 3.20 Fragment Processing Functions

### ISSUE THREAD

**Issue by afd** [google/graphicsfuzz#468]
Section 8.14 of the [GLSL ES 3.20 specification](https://www.khronos.org/registry/OpenGL/specs/es/3.2/GLSL_ES_Specification_3.20.pdf) defines Fragment Processing functions.

Support for these functions should be made complete.

- TyperHelper::getBuiltinsForGlslVersion should get the builtins of this kind by invoking a helper function, getBuiltinsForGlslVersionFragmentProcessing

- This new method should return templates for all of the functions specified in Section 8.14 of the GLSL ES 3.20 specification if the shading language version is ESSL_320.

- If the shading language version is different from ESSL_320, templates for all of the GLSL ES 3.20 builtins from Section 8.14 that are available in the particular shading language version should be returned.

The test functions, "testBuiltins[shadinglanguageversion]" in TyperTest should already serve to ensure that inappropriate builtins for a shading language version are not generated.

**Comment by abelbriggs1** [comment]
Fixed by #549.
