### ISSUE TITLE
runspv/amber: Vulkan::Calling vkWaitForFences Fail

### ISSUE THREAD

**Issue by paulthomson** [google/graphicsfuzz#485]
Sometimes, Vulkan calls can fail. Typically, this is because a shader was timed out by the driver/OS/watchdog before our 30 second time limit was reached. Amber will still try to dump buffers (image or compute output buffer), which is intentional. However, it can then fail an assertion. Even if it did not, the buffer is likely to be undefined.

runspv (or whatever script runs shaders) should check for various "Vulkan::Calling X" messages and fail the test with a TIMEOUT status or some other status to distinguish it from other crashes.

**Comment by afd** [comment]
Closing this as it's an Amber issue - if it's still a problem we should open an issue there. @paulthomson for info.
