### ISSUE TITLE
Enhance identity transformation to rewrite matrix variable

### ISSUE THREAD

**Issue by afd** [google/graphicsfuzz#517]
Currently, thanks to #512, we can rewrite e.g. a mat2x2, m, to e.g. mat2x2(m[0], IDENTITY(m[1])).

It would be nice if we also gave the fuzzer the option to rewrite the matrix as e.g. mat2x2(m[0][0], IDENTITY(m[0][1]), m[1][0], m[1][1]).  (I may not have got this right - can never remember whether rows or columns come first in GLSL!).

**Comment by abelbriggs1** [comment]
Fixed by #527.
