### ISSUE TITLE
Write new versions of GraphicsFuzz reference shaders that use Integer Functions

### ISSUE THREAD

**Issue by afd** [google/graphicsfuzz#543]
For each shader, foo.frag, in shaders/src/main/glsl/samples/310es, produce a version, foo_integer_functions.frag that is semantically equivalent to foo.frag but that makes significant use of Integer Functions.

In addition, foo_integer_functions.frag may make use of control flow that is available in GLSL ES 3.10 but not GLSL ES 1.00, for example while loops, do...while loops, switch statements, and for loops with empty header components.

**Comment by abelbriggs1** [comment]
Fixed by #605
