### ISSUE TITLE
Enable and fix image tests

### ISSUE THREAD

**Issue by paulthomson** [google/graphicsfuzz#62]

**Comment by paulthomson** [comment]
The image test failures are still a mystery. Here is a log:

https://api.travis-ci.org/v3/job/478349485/log.txt

Search for "Result: 139"

It seems that `get_image_egl` (the version that uses swiftshader) is failing with SIGSEGV. I believe this is just on a reference shader: `mandelbrot_blurry.json.reference.frag`.

It does not repro locally with Docker.

**Comment by paulthomson** [comment]
Log with backtraces: https://api.travis-ci.org/v3/job/481380742/log.txt

Search for: "Program received signal"

I will try with the debug version of swiftshader

**Comment by paulthomson** [comment]
PR #276 addresses this

**Comment by afd** [comment]
@paulthomson I suggest we close this - the frequency with which we decide to run them is more of a process matter than a technical issue.

**Comment by paulthomson** [comment]
Fixed in #276
