### ISSUE TITLE
Opaque zero / opaque one idea: dot operator

### ISSUE THREAD

**Issue by afd** [google/graphicsfuzz#634]
For two vectors, v1 and v2 of the same length:

- If v1[i] != 0 <=> v1[i] = 0 then dot(v1, v2) = 0.  This requires all non-zero components are finite (no infinities, no NaNs).  So we could simplify things to construct vectors that are 0 or 1 everywhere, and never 1 in the same place.

- If v1[i] = v2[i] = 0 for all i different from some single index j, and if v[j] = v[i] = 1, then dot(v1, v2) = 1.

**Comment by abelbriggs1** [comment]
Fixed by #642.
