### ISSUE TITLE
Opaque zero idea: cross product of vec3 with itself

### ISSUE THREAD

**Issue by afd** [google/graphicsfuzz#636]
For a vec3 v, cross(v, v) is zero (assuming v contains only finite components).

For an existing side-effect free vector expression e, we could make zero via cross(e, e).  There is a risk that the result might be strange if e contains infinities or NaNs, but if this is an existing expression then the risk of weird stuff happening due to non-finite values would already be there.

**Comment by abelbriggs1** [comment]
Fixed by #682.
