### ISSUE TITLE
Be less conservative with matrix functions in constexpr contexts

### ISSUE THREAD

**Issue by abelbriggs1** [google/graphicsfuzz#653]
Due to [this](https://github.com/KhronosGroup/glslang/issues/1865) issue in glslangvalidator, some matrix functions will cause test failures in GraphicsFuzz when used in constexpr contexts - we developed workarounds for PRs #648 and #649, but when this issue is fixed it'd be good to revert those.

**Comment by afd** [comment]
Closing this since, as discussed in https://github.com/KhronosGroup/glslang/issues/1865, regarding these functions as non-compile-time-constant is intentional.
