### ISSUE TITLE
ExpressionGenerator: wrap the generated expressions in _GLF_IDENTITY

### ISSUE THREAD

**Issue by jiradeto** [google/graphicsfuzz#662]
To allow reducer to reduce the expressions generated by ExpressionGenerator, we should wrap all expressions that generate value in _GLF_IDENTITY. 

For example, if we are representing 42 as 20 + 22:
```
_GLF_IDENTITY(42, _GLF_IDENTITY(20, expr_generating_20), _GLF_IDENTITY(22, expr_generating_22)))
```

**Comment by afd** [comment]
Closing as we are retiring the known-value shader generator.
