### ISSUE TITLE
Generator donates case outside switch statement 

### ISSUE THREAD

**Issue by jiradeto** [google/graphicsfuzz#665]
This [Archive.zip](https://github.com/google/graphicsfuzz/files/3484283/Archive.zip) contains the original and the variant shaders generated by a test`testGenerateSmallVulkanShaderFamilyWithReferencesAsDonors` which shows that there is the injected case that appears outside the switch statement. This results in the validation error: 
```
variant_000.frag
ERROR: 0:312: 'case' : cannot appear outside switch statement
ERROR: 0:312: '' : compilation terminated
ERROR: 2 compilation errors.  No code generated.
```

**Comment by afd** [comment]
Fixed via #666.
