### ISSUE TITLE
MakeArrayAccessesInBounds can duplicate side effects and does not handle nested arrays indices well

### ISSUE THREAD

**Issue by afd** [google/graphicsfuzz#679]
Not a huge issue, since MakeArrayAccessesInBounds is mainly applied to live-injected code, but:

- by turning A[e] into "A[inBounds(e) ? e : 0]" we cause any side effects committed by "e" to be applied more than once

- if we have A[B[e]] then we will end up cloning B[e] when making the access to A in bounds, and then only making one of the copies of B[e] in bounds, so we'll end up with something like:

   A[inBounds(B[inBounds(e) ? e : 0]) ? B[e] : 0); // second B[e] might not be in bounds

A solution to both problems would be to turn A[e] into:

temp = e; // recursively make 'e' in bounds if it contains array accesses
... A[inBounds(temp) ? temp : 0]

So that A[B[x + y]], say, would become something like:

temp1 = x + y;
temp2 = B[inBounds(temp1) ? temp1 : 0];
... A[inBounds(temp2) ? temp2 : 0] ...

**Comment by paulthomson** [comment]
I have another instance of this issue:

```c
int A[10];
A[++i >= 0 && ++i < 10 ? i : 0] = 123;
```

This is a bit more problematic, as I think it is causing out of bound accesses and possibly leading to stack corruption.

**Comment by afd** [comment]
Fixed via #752.
