### ISSUE TITLE
Portability Flaw: File Separator

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/graphicsfuzz#730]
https://github.com/google/graphicsfuzz/blob/143f46a1298a2a1e012b8b3ab31fc87c2075e82f/server/src/main/java/com/graphicsfuzz/server/webui/AccessFileInfo.java#L53
The path split symbol problem is different for different operating systems. Hard-coded file separators should not be used. Instead, use a platform-independent API provided by the language library, such as java.io.File.separator, or by using java.lang.System.getProperty("file.separator") Obtain.

**Comment by afd** [comment]
We should retire the WebUI in favour of gfauto, especially once we have ShaderTrap integration, thus closing WebUI-related issues.
