### ISSUE TITLE
Investigate whether binarysearch_tree shader is stable

### ISSUE THREAD

**Issue by afd** [google/graphicsfuzz#739]
[binarysearch_tree.zip](https://github.com/google/graphicsfuzz/files/3609887/binarysearch_tree.zip)

I have been finding that the 'binarysearch_tree' shader that ships with the GraphicsFuzz samples gives significantly different reference images across various devices.

In particular, I get noticeably different images when running the shader using SwiftShader, vs. using Intel Mesa.  (Those would be suitable to investigate this issue, but so would any two Vulkan implementations that give significantly different results.)

This means that either:

(1) one of SwiftShader or Intel Mesa has a shader compiler bug
or
(2) the shader is not numerically stable

The goal of this issue is to investigate which is the case.

If it is (1), an issue should be filed against the appropriate open source tool.

If it is (2), a proposal for how to fix the shader to make it stable should be made.

I suggest approaching this by manually simplifying the shader so that it renders a successively simpler image, to gain confidence that that image is predictable, but at the same time checking that different images are rendered by SwiftShader and Intel Mesa.

This will either end up leading to a very small, easy-to-understand shader that exposes a bug in one of the drivers, or will lead to the source of floating-point instability if that is indeed the problem.

Do:

runspv host reference.json outdir

to run the shader, after which outdir/image_0.png will contain the rendered image.

The attached zip has the reference shader and .json file, plus the two images I am seeing.

**Comment by jarikomppa** [comment]
The shader appears to be dependent on the precision of the floating point used. The shader declares highp, which should(?) mean 32 bit floats currently.

I ported the shader to c++, and using float as the variable type I got nearly, but not exactly the same image as the reference / swiftshader (pixel values varied by 1 in the range of 256). If I switched to doubles, I got even distinctly different image, even bigger difference than with the mesa image.

So while the shader is somewhat dependent on floating point precision, I'm suspecting that something is also going wrong with mesa, but the spec is not precise on the precision requirements, so there may be a bit of wiggle room there (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/chap2.html#fundamentals-numerics).

**Comment by afd** [comment]
Thanks!  Could you look at doing something to the colour computation in the shader that would suppress the large difference you see with double precision?

The shader does something very deterministic related to sorting, and then does some magic to get an interesting colour pattern.  A less interesting colour pattern that is less floating-point sensitive would be preferable; can you have a go at that?

**Comment by jarikomppa** [comment]
Yeah, it should be relatively simple to do a test bench that calculates
with both floats and doubles, and then to iterate some small changes until
I get a (more) stable shader.

**Comment by jarikomppa** [comment]
The offending bit is the sinh() function. Replacing it with some other trig function like sin() or tan() will change the colors around a bit, but it still looks more or less as interesting. I'd go with tan(). The inputs of that function range from [-5,45] which makes sinh completely blow up, but the average is around 3.2, and tan() looks interesting enough on that range.

**Comment by afd** [comment]
Thanks!

Could you please do a PR to fix this in the two versions of that shader in the GraphicsFuzz repo?  They are under graphicsfuzz/shaders/src/main/glsl/samples/300es and graphicsfuzz/shaders/src/main/glsl/samples/310es

**Comment by jarisiru** [comment]
https://github.com/google/graphicsfuzz/pull/746

**Comment by afd** [comment]
Fixed via #746
