### ISSUE TITLE
Investigate stability of mergesort_mosaic shader

### ISSUE THREAD

**Issue by afd** [google/graphicsfuzz#749]
Similar to #739, the mergesort_mosaic shader gives pretty different results across platforms.  In particular, Swiftshader and Intel Mesa give rather different results.

@jarikomppa would you be able to take a look and see whether it is possible to fix the trig functions to get something more stable?

**Comment by jarikomppa** [comment]
At first glance I noticed that the shader uses the functions acosh() and asinh() which I expected to be the problem, but it wasn't.

First pass of the c++ conversion gives me identical images between float and double, but not identical with the golden image. The shader also uses dFdy() for which I don't have an implementation, and the spir-v spec is slightly vague on the specifics, but it does say there's diffferent ways of implementing it, so it may be a good idea to replace that function. I replaced it simply by returning whatever it receives, and this apparently matches the golden image.

Still investigating, but things look better than I expected at the first glance.

**Comment by afd** [comment]
Thanks!  I was quite keen to include dFdy in some of our references - it's a fragment processing function and has the requirement that it should be reached under uniform control flow (so that all or no fragments reach it).  I figured it could be good to see whether transforming a shader that uses it leads to interesting mis-optimizations.  But I agree that the vagueness of the spec with respect to this function makes things hard!

**Comment by jarikomppa** [comment]
The line in the golden image that is produced via dFdy seems pretty good in most of the result images though, so maybe(?) it's fine.

**Comment by jarikomppa** [comment]
acosh() gets a value below 1, where by spir-v spec the result is undefined. That explains the difference between golden and my c++ code. C++ says nan, but vulkan spec says nan and inf are optional.

**Comment by jarikomppa** [comment]
Adding clamp(...,1,1000) to the acosh() parameter seems to fix the problem. Also, dFdy shouldn't return the y coordinate but the constant of stepping through fragments/pixels, i.e, 1, so I'm pretty sure it's fine in this case. If the surface was slanted (instead of screen-facing), the result might vary.

There's also a couple of tricky undefined calculations where the results are ignored (like calculating something for a vector where some elements are undefined, but never accessed), but those should be fine.

**Comment by jarikomppa** [comment]
So the offending line would change from:
`color = fract(acosh(vecCoor.yx - trunc(float(data[3]))));`
to:
`color = fract(acosh(clamp(vecCoor.yx - trunc(float(data[3])),1,1000));`

Is that ok, or do I break something I don't know about?

**Comment by afd** [comment]
Thanks for the explanation!

From my point of view that change is fine (though for our preferred style can you please put spaces after commas?)

@jiradeto wrote this shader and I believe the use of trigonometric functions was a bit experimental - to try to get some interesting patterns and colours rather than with a specific goal in mind, so I don't think there's anything for your change to break as such.

**Comment by jarisiru** [comment]
https://github.com/google/graphicsfuzz/pull/753

**Comment by jiradeto** [comment]
> Thanks for the explanation!
> 
> From my point of view that change is fine (though for our preferred style can you please put spaces after commas?)
> 
> @jiradeto wrote this shader and I believe the use of trigonometric functions was a bit experimental - to try to get some interesting patterns and colours rather than with a specific goal in mind, so I don't think there's anything for your change to break as such.

Yes, my idea was trying to apply various built-in functions to get diversely interesting results. Thus, feel free to modify.

**Comment by afd** [comment]
Fixed via #753.
