### ISSUE TITLE
Array size should be an Expr

### ISSUE THREAD

**Issue by paulthomson** [google/graphicsfuzz#766]
The size of an array is currently stored as an int. GraphicsFuzz fails at the parsing stage if the size of an array in a shader is not a trivial int literal. (E.g. trivial is 5; non-trivial is 4+1)

GraphicsFuzz rarely needs the size as an int; it could just use the expression. 

- [x] Change the parser and ArrayInfo class to store the array size as an Expr, not as an int.
- [x] Change the uses of `ArrayInfo.getSize()` to just use the new method `getSizeExpr()`. It might be a good idea to keep `getSize()`, making it return the size as an int when the expression is an int literal, or throwing an exception otherwise. We could even add some simple, on-demand constant folding if needed, but I doubt it will actually be needed.

**Comment by afd** [comment]
Fixed via #777.
