### ISSUE TITLE
Windows Batch -> Python not working as intended.

### ISSUE THREAD

**Issue by bakpakin** [google/graphicsfuzz#801]
I am trying to GraphicsFuzz on windows with a pretty standard setup. However, I am having problems when I remove python3 installed on the machine in the default location and add a custom installation of python to PATH. The python/drivers directory contains many short batch files for detecting a python 3 executable, one of  py, python3, or python in that order. However, regardless of what python version is actually available, the script attempts to use py.exe.

This seems to be due to an incorrect use of IF ERRORLEVEL 0 in the scripts, which will be true if %errorlevel% is 0 _or greater than 0_, thus always choosing to use py, even if not actually detected. I think a fix should be pretty simple.

**Comment by paulthomson** [comment]
Thanks for catching this! This should be fixed in #811. You can checkout the `dev` branch to try it.
