### ISSUE TITLE
About Fuzzy diff algorithm

### ISSUE THREAD

**Issue by amm040341** [google/graphicsfuzz#937]
Hi, 

I want to ask about the comparison method: fuzzy diff

Since you mentioned in glsl-fuzz walkthrough
**The histogram comparison compares the overall colors of the images up to some default threshold, while the fuzzy diff algorithm compares pixel locations with various thresholds for pixel-movement and color variation.**
And from paper 'Automated Testing of Graphics Shader Compilers' I know: 
        Histogram comparison used OpenCV function - compareHist to calculate the diff and its threshold is 100.0. 

How about the implementation of 'fuzzy diff algorithm'? Do you have any reference can provide? Thanks a lot!

**Comment by paulthomson** [comment]
I'm afraid the only reference is the implementation:
https://github.com/google/graphicsfuzz/blob/master/common/src/main/java/com/graphicsfuzz/common/util/FuzzyImageComparison.java#L396

It is not based on any literature.

**Comment by amm040341** [comment]
This is helpful to me. Thank you so much!
