### ISSUE TITLE
Convert frag->vert and support rendering the shader jobs via a grid of quads

### ISSUE THREAD

**Issue by paulthomson** [google/graphicsfuzz#941]
FragmentShaderJobToVertexShaderJobConverter

* [ ] A Java tool to convert a fragment shader job to a "vertex shader job".
  * Assume the original framebuffer was 256x256. The uniforms do not need to change. Add key `"$grid": { "width": 256, "height": 256},`.
  * gl_FragCoord.x -> ...something based on vertex position.
* [ ] Maybe add something to GraphicsFuzz to ignore $grid. Check that you can run GlslGenerate on the shader jobs.
* [ ] gfauto: change Amberfy code. Detect the $grid key and react accordingly.

**Comment by Jaikishan-Saroj** [comment]
can i Work on it ?? @paulthomson

**Comment by paulthomson** [comment]
Sorry this has actually already been completed.

**Comment by paulthomson** [comment]
Closed by the following PRs: #954, #956, #974
